project:
  type: website
  output-dir: docs

website:
  title: "logbook"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rodserr
      - icon: linkedin
        href: https://www.linkedin.com/in/rodrigo-serrano-morales/
format:
  html:
    theme: lux
    css: styles.css

editor: source

